<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.undertow</groupId>
  <artifactId>undertow-spring-boot-parent</artifactId>
  <version>1.0.0.Final-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>undertow-spring-boot-parent</name>
  <description>Parent POM for Spring Boot Undertow modules</description>
  <url>https://spring.io/projects/spring-boot</url>


  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>

  <modules>
    <module>module/undertow-spring-boot-autoconfigure</module>
    <module>starter/undertow-spring-boot-starter</module>
  </modules>

  <properties>
    <java.version>17</java.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <spring-boot.version>4.1.0</spring-boot.version>
    <undertow.version>2.0.1.Final</undertow.version>

    <!-- Checkstyle and SpotBugs -->
    <version.io.undertow.build.checkstyle-config>2.0.0.Final</version.io.undertow.build.checkstyle-config>
    <version.com.github.spotbugs-maven-plugin>4.9.8.3</version.com.github.spotbugs-maven-plugin>
    <spotbugs.exclude.filter.file>${maven.multiModuleProjectDirectory}/spotbugs-exclude.xml</spotbugs.exclude.filter.file>
    <linkXRef>false</linkXRef>
  </properties>

  <dependencyManagement>
    <dependencies>

      <!-- Spring Boot BOM (manages Spring Boot, Spring Framework, Micrometer, etc.) -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <!-- Undertow -->
      <dependency>
        <groupId>io.undertow.ee</groupId>
        <artifactId>undertow-servlet</artifactId>
        <version>${undertow.version}</version>
      </dependency>
      <dependency>
        <groupId>io.undertow.ee</groupId>
        <artifactId>undertow-websockets</artifactId>
        <version>${undertow.version}</version>
      </dependency>


    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
          <configuration>
            <release>${maven.compiler.release}</release>
            <encoding>${project.build.sourceEncoding}</encoding>
            <skipMain>false</skipMain> <!-- keep compiling main sources -->
            <skip>true</skip>          <!-- skip test source compilation because it depends on some test framework in SpringBoot code base-->
                                       <!-- which isn't published as maven artifacts  -->
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.2.5</version>
          <configuration>
            <skipTests>true</skipTests>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>3.6.0</version>
          <configuration>
            <configLocation>undertow-checkstyle/checkstyle.xml</configLocation>
            <consoleOutput>true</consoleOutput>
            <failsOnError>true</failsOnError>
            <includeTestSourceDirectory>true</includeTestSourceDirectory>
            <useFile/>
            <sourceDirectories>
              <sourceDirectory>${project.build.sourceDirectory}</sourceDirectory>
            </sourceDirectories>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>io.undertow.build</groupId>
              <artifactId>undertow-checkstyle-config</artifactId>
              <version>${version.io.undertow.build.checkstyle-config}</version>
            </dependency>
          </dependencies>
          <executions>
            <execution>
              <id>check-style</id>
              <phase>compile</phase>
              <goals>
                <goal>checkstyle</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-maven-plugin</artifactId>
          <version>${version.com.github.spotbugs-maven-plugin}</version>
          <configuration>
            <excludeFilterFile>${spotbugs.exclude.filter.file}</excludeFilterFile>
          </configuration>
          <executions>
            <execution>
              <id>find-bugs</id>
              <phase>verify</phase>
              <goals>
                <goal>check</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <profiles>
    <profile>
      <id>spotbugs</id>
      <activation>
        <property>
          <name>findbugs</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
